### ISSUE TITLE
Format of license key?

### ISSUE THREAD

**Issue by elvinup** [reteps/McdonaldsOnline#2]
So im able to sniff, but unsure if it's my fault or if the code is outdated now?

is it called the mcd_apikey?
i put that in as Client('mcd_apikey i sniffed')
and then put in my email and password but i just get this error:
`
File "mcdonald.py", line 79, in _check_for_error
    if response["ResultCode"] != 1:
KeyError: 'ResultCode'
`

If it's not the mcd_apikey, what would it be then?

**Comment by reteps** [comment]
i haven't touched this code in a while, most likely outdated. It's saying that `ResultCode` no longer exists, which could be a result of a different api system.

**Comment by flaryx32** [comment]
> i haven't touched this code in a while, most likely outdated. It's saying that `ResultCode` no longer exists, which could be a result of a different api system.


Yo hmmmm, I know this is very very very very old, but could you maybe give a try to reverse the new api? Sry for re opening the issue :/
